# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

meboot_approx <- function(p, n, z, desintxb) {
    .Call(`_simulatetimeseries_meboot_approx`, p, n, z, desintxb)
}

meboot_part_rcpp <- function(x, reps, z, xmin, xmax, desintxb, reachbnd) {
    .Call(`_simulatetimeseries_meboot_part_rcpp`, x, reps, z, xmin, xmax, desintxb, reachbnd)
}

expand_sd_rcpp <- function(x, ensemble, fiv = 1.0, elbow = 0.95, force_clt = FALSE) {
    .Call(`_simulatetimeseries_expand_sd_rcpp`, x, ensemble, fiv, elbow, force_clt)
}

expand_sd_rcpp_fast <- function(x, ensemble, fiv = 1.0, elbow = 0.95) {
    .Call(`_simulatetimeseries_expand_sd_rcpp_fast`, x, ensemble, fiv, elbow)
}

simpson_integral_cpp <- function(x, y) {
    .Call(`_simulatetimeseries_simpson_integral_cpp`, x, y)
}

